### ISSUE TITLE
hhvm: symbol lookup error: hhvm: undefined symbol: mallocx

### ISSUE THREAD

**Issue by alberteddu** [vicb/hhvm-vagrant#2]
Hi,

thanks for this repository, can't wait to play with hhvm. I just cloned the repo and ran "vagrant up", but I get the error:

```
hhvm: symbol lookup error: hhvm: undefined symbol: mallocx
```

I get it also when running the hhvm service with `sudo service hhvm start`. Am I missing something?

**Comment by Mikulas** [comment]
:+1:  fails on my setup as well

**Comment by vicb** [comment]
Sorry guys I am on vacation this week and I can't check. If someone can send a PR before I can look at this next week, I'll merge that.

**Comment by ClaudiuC** [comment]
I think this was patched yesterday, see the referenced issue ^

**Comment by vicb** [comment]
@ClaudiuC thanks for the reference. I'll check and close this when I'm back in the coming days.
