### ISSUE TITLE
Hack not working after setting up box

### ISSUE THREAD

**Issue by keyboSlice** [vicb/hhvm-vagrant#6]
Hi there, I was wondering if you could help me, I followed the instructions for installation however Hack files are not working on the box - if I replace the default hack index.php in the www directory with <?php echo 'PHP works!'; then I see the correct output, however swapping that code with <?hh echo 'Hack works!'; I get just a white screen, please can you advise if I have missed out any configuration steps?

Thanks in advance,

Keir

**Comment by keyboSlice** [comment]
My apologies, I had not followed the steps in this guide :   http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php

to get Hack running on the box

**Comment by vicb** [comment]
If this resolves your issue, you can close this (I'll add the guide to the doc)
